class PotRunner
{
	public static void main(String[] args)
	{
		System.out.println("Running main");
		Pot pot=new Pot("red",50,60,89,true,"Storing water","clay",3);
		System.out.println(pot.color);
		System.out.println(pot.price);
		System.out.println(pot.volume);
		System.out.println(pot.height);
		System.out.println(pot.inGoodCondition);
		System.out.println(pot.use);
		System.out.println(pot.material);
		System.out.println(pot.durability);
		Pot pot1=new Pot("green",40,55,90,false,"cooking","porcelain",4);
		System.out.println(pot1.color);
		System.out.println(pot1.price);
		System.out.println(pot1.volume);
		System.out.println(pot1.height);
		System.out.println(pot1.inGoodCondition);
		System.out.println(pot1.use);
		System.out.println(pot1.material);
		System.out.println(pot1.durability);
		Pot pot2=new Pot("blue",35,40,56,true,"Storing sause","Stoneware",5);
		System.out.println(pot2.color);
		System.out.println(pot2.price);
		System.out.println(pot2.volume);
		System.out.println(pot2.height);
		System.out.println(pot2.inGoodCondition);
		System.out.println(pot2.use);
		System.out.println(pot2.material);
		System.out.println(pot2.durability);
		Pot pot3=new Pot("orange",45,50,75,false,"cooking meat","terra cotta",7);
		System.out.println(pot3.color);
		System.out.println(pot3.price);
		System.out.println(pot3.volume);
		System.out.println(pot3.height);
		System.out.println(pot3.inGoodCondition);
		System.out.println(pot3.use);
		System.out.println(pot3.material);
		System.out.println(pot3.durability);
		Pot pot4=new Pot("Olive",54,43,84,true,"Cooking","Plasticine",2);
		System.out.println(pot4.color);
		System.out.println(pot4.price);
		System.out.println(pot4.volume);
		System.out.println(pot4.height);
		System.out.println(pot4.inGoodCondition);
		System.out.println(pot4.use);
		System.out.println(pot4.material);
		System.out.println(pot4.durability);
		Pot pot5=new Pot("pink",25,30,44,false,"boiling liquids","Modelling clay",8);
		System.out.println(pot5.color);
		System.out.println(pot5.price);
		System.out.println(pot5.volume);
		System.out.println(pot5.height);
		System.out.println(pot5.inGoodCondition);
		System.out.println(pot5.use);
		System.out.println(pot5.material);
		System.out.println(pot5.durability);
		Pot pot6=new Pot("black",45,63,78,true,"Cooking fish","Earthernware clay",6);
		System.out.println(pot6.color);
		System.out.println(pot6.price);
		System.out.println(pot6.volume);
		System.out.println(pot6.height);
		System.out.println(pot6.inGoodCondition);
		System.out.println(pot6.use);
		System.out.println(pot6.material);
		System.out.println(pot6.durability);
		Pot pot7=new Pot("white",63,32,42,false,"Storing sauces","Bentonite",2);
		System.out.println(pot7.color);
		System.out.println(pot7.price);
		System.out.println(pot7.volume);
		System.out.println(pot7.height);
		System.out.println(pot7.inGoodCondition);
		System.out.println(pot7.use);
		System.out.println(pot7.material);
		System.out.println(pot7.durability);
	}
}