class SofaRunner
{
	public static void main(String[] args)
	{
	System.out.println("Running main");
	Sofa sofa=new Sofa("blue",4,50,true,20000,150.5,90.5,false);
	System.out.println(sofa.color);
	System.out.println(sofa.capacity);
	System.out.println(sofa.weight);
	System.out.println(sofa.inGoodCondition);
	System.out.println(sofa.cost);
	System.out.println(sofa.length);
	System.out.println(sofa.width);
	System.out.println(sofa.comfortable);
	Sofa sofa1=new Sofa("yellow",3,48,false,30000,145.5,80.5,false);
	System.out.println(sofa1.color);
	System.out.println(sofa1.capacity);
	System.out.println(sofa1.weight);
	System.out.println(sofa1.inGoodCondition);
	System.out.println(sofa1.cost);
	System.out.println(sofa1.length);
	System.out.println(sofa1.width);
	System.out.println(sofa1.comfortable);
	Sofa sofa2=new Sofa("Red",5,45,true,19000,154.5,91.5,false);
	System.out.println(sofa2.color);
	System.out.println(sofa2.capacity);
	System.out.println(sofa2.weight);
	System.out.println(sofa2.inGoodCondition);
	System.out.println(sofa2.cost);
	System.out.println(sofa2.length);
	System.out.println(sofa2.width);
	System.out.println(sofa2.comfortable);
	Sofa sofa3=new Sofa("green",5,60,false,16000,160.5,80.5,true);
	System.out.println(sofa3.color);
	System.out.println(sofa3.capacity);
	System.out.println(sofa3.weight);
	System.out.println(sofa3.inGoodCondition);
	System.out.println(sofa3.cost);
	System.out.println(sofa3.length);
	System.out.println(sofa3.width);
	System.out.println(sofa3.comfortable);
	Sofa sofa4=new Sofa("orange",6,65,true,17000,150,70.5,false);
	System.out.println(sofa4.color);
	System.out.println(sofa4.capacity);
	System.out.println(sofa4.weight);
	System.out.println(sofa4.inGoodCondition);
	System.out.println(sofa4.cost);
	System.out.println(sofa4.length);
	System.out.println(sofa4.width);
	System.out.println(sofa4.comfortable);
	Sofa sofa5=new Sofa("pink",7,30,false,18000,165.5,70.5,false);
	System.out.println(sofa5.color);
	System.out.println(sofa5.capacity);
	System.out.println(sofa5.weight);
	System.out.println(sofa5.inGoodCondition);
	System.out.println(sofa5.cost);
	System.out.println(sofa5.length);
	System.out.println(sofa5.width);
	System.out.println(sofa5.comfortable);
	Sofa sofa6=new Sofa("peach",5,35,true,14000,170.5,95.5,true);
	System.out.println(sofa6.color);
	System.out.println(sofa6.capacity);
	System.out.println(sofa6.weight);
	System.out.println(sofa6.inGoodCondition);
	System.out.println(sofa6.cost);
	System.out.println(sofa6.length);
	System.out.println(sofa6.width);
	System.out.println(sofa6.comfortable);
	Sofa sofa7=new Sofa("olive",7,44,false,18500,139.5,85.5,false);
	System.out.println(sofa7.color);
	System.out.println(sofa7.capacity);
	System.out.println(sofa7.weight);
	System.out.println(sofa7.inGoodCondition);
	System.out.println(sofa7.cost);
	System.out.println(sofa7.length);
	System.out.println(sofa7.width);
	System.out.println(sofa7.comfortable);
	}
}
